### ISSUE TITLE
PHP notice after activation

### ISSUE THREAD

**Issue by danielvonmitschke** [anttiviljami/woocommerce-clean-orphaned-variations#1]
nothing serious but a php notice is shown after activating the plugin:

> Notice: Undefined index: page in /Users/daniel/Sites/soohotrightnow.com2/web/app/plugins/woocommerce-clean-orphaned-variations/woocommerce-clean-orphaned-variations.php on line 85

maybe you should first check for " empty( $_REQUEST['page'] )

daniel

**Comment by danielvonmitschke** [comment]
Ok, this is a better approach.
Just insert at the beginning of your handle_woocommerce_tool method:

```
      if( empty( $_REQUEST['page'] ) || empty( $_REQUEST['tab'] ) ) {
          return;
      }
```

**Comment by anttiviljami** [comment]
absolutely. :) want to make a pull request?

**Comment by danielvonmitschke** [comment]
done :)

**Comment by anttiviljami** [comment]
Thank you! :)

**Comment by anttiviljami** [comment]
And if you could, please leave a star for this Github repo so that other people can find this more easily! :)
